name=RadioCore Library
version=0.0.1
author=Heltec Automation
maintainer=Heltec Automation <support@heltec.cn>
sentence=Arduino library for RadioCore series hardware.
paragraph=Provides a standard foundation for RadioCore hardware support and declares the Adafruit BME280 Library as a dependency.
category=Device Control
url=https://github.com/Quency-D/RadioCore_Library
architectures=*
includes=RadioCore.h
depends=Adafruit BME280 Library
