#ifndef RADIOCORE_BOARD_HELTEC_RC32_H
#define RADIOCORE_BOARD_HELTEC_RC32_H

#include <Arduino.h>
#include <Wire.h>

#define RADIOCORE_HAS_SENSOR_I2C 1
#define RADIOCORE_SENSOR_I2C_INSTANCE Wire
#define RADIOCORE_SENSOR_I2C_SDA 21
#define RADIOCORE_SENSOR_I2C_SCL 18
#define RADIOCORE_SENSOR_I2C_DEFAULT_FREQUENCY 100000UL

#define RADIOCORE_HAS_SENSOR_POWER_CTRL 1
#define RADIOCORE_SENSOR_POWER_CTRL_PIN 46
#define RADIOCORE_SENSOR_POWER_ON HIGH
#define RADIOCORE_SENSOR_POWER_WARMUP_MS 100UL

#define RADIOCORE_HAS_CH01_ADC 1
#define RADIOCORE_CH01_ADC_PIN 2
#define RADIOCORE_HAS_CH01_POWER_CTRL 1
#define RADIOCORE_CH01_POWER_CTRL_PIN 46
#define RADIOCORE_CH01_POWER_ON HIGH
#define RADIOCORE_CH01_POWER_WARMUP_MS 100UL

#endif // RADIOCORE_BOARD_HELTEC_RC32_H
