#ifndef RADIOCORE_BOARD_HELTEC_RCC6_H
#define RADIOCORE_BOARD_HELTEC_RCC6_H

#include <Arduino.h>
#include <Wire.h>

#define RADIOCORE_HAS_SENSOR_I2C 1
#define RADIOCORE_SENSOR_I2C_INSTANCE Wire
#define RADIOCORE_SENSOR_I2C_SDA SDA
#define RADIOCORE_SENSOR_I2C_SCL SCL
#define RADIOCORE_SENSOR_I2C_DEFAULT_FREQUENCY 100000UL

#define RADIOCORE_HAS_SENSOR_POWER_CTRL 0

#define RADIOCORE_HAS_CH01_ADC 0
#define RADIOCORE_HAS_CH01_POWER_CTRL 0
#define RADIOCORE_HAS_VO01_ADC 0
#define RADIOCORE_HAS_VO01_POWER_CTRL 0
#define RADIOCORE_HAS_CO01_ADC 0
#define RADIOCORE_HAS_CO01_POWER_CTRL 0

#define RADIOCORE_HAS_NV3001B_DISPLAY 1
#define RADIOCORE_NV3001B_BOARD_NAME "Heltec RCC6"
#define RADIOCORE_NV3001B_USE_ESP32_SPI 0
#define RADIOCORE_NV3001B_USE_HARDWARE_SPI 0
#define RADIOCORE_NV3001B_USE_SOFTWARE_SPI 1
#define RADIOCORE_NV3001B_SCK 4
#define RADIOCORE_NV3001B_MOSI 15
#define RADIOCORE_NV3001B_MISO -1
#define RADIOCORE_NV3001B_CS 18
#define RADIOCORE_NV3001B_DC 3
#define RADIOCORE_NV3001B_RST 0
#define RADIOCORE_NV3001B_ENABLE 2
#define RADIOCORE_NV3001B_ENABLE_ACTIVE LOW
#define RADIOCORE_NV3001B_BACKLIGHT 1
#define RADIOCORE_NV3001B_BACKLIGHT_ACTIVE HIGH
#define RADIOCORE_NV3001B_SPI_FREQUENCY 8000000UL

#endif // RADIOCORE_BOARD_HELTEC_RCC6_H
