#ifndef RADIOCORE_BOARD_HELTEC_RCC6_H
#define RADIOCORE_BOARD_HELTEC_RCC6_H

#include <Arduino.h>
#include <Wire.h>

#define RADIOCORE_HAS_SENSOR_I2C 1
#define RADIOCORE_SENSOR_I2C_INSTANCE Wire
#define RADIOCORE_SENSOR_I2C_SDA SDA
#define RADIOCORE_SENSOR_I2C_SCL SCL
#define RADIOCORE_SENSOR_I2C_DEFAULT_FREQUENCY 100000UL

#define RADIOCORE_HAS_SENSOR_POWER_CTRL 0

#define RADIOCORE_HAS_CH01_ADC 0
#define RADIOCORE_HAS_CH01_POWER_CTRL 0

#endif // RADIOCORE_BOARD_HELTEC_RCC6_H
