#ifndef RADIOCORE_BOARD_HELTEC_RC52_H
#define RADIOCORE_BOARD_HELTEC_RC52_H

#include <Arduino.h>
#include <Wire.h>

#define RADIOCORE_HAS_SENSOR_I2C 1
#define RADIOCORE_SENSOR_I2C_INSTANCE Wire
#define RADIOCORE_SENSOR_I2C_SDA (32 + 11) // P1.11
#define RADIOCORE_SENSOR_I2C_SCL (0 + 2)   // P0.02
#define RADIOCORE_SENSOR_I2C_DEFAULT_FREQUENCY 100000UL

#define RADIOCORE_HAS_SENSOR_POWER_CTRL 1
#define RADIOCORE_SENSOR_POWER_CTRL_PIN (0 + 12)
#define RADIOCORE_SENSOR_POWER_ON HIGH
#define RADIOCORE_SENSOR_POWER_WARMUP_MS 100UL

#endif // RADIOCORE_BOARD_HELTEC_RC52_H
